"""inferhub-client — a small, typed Python client for InferHub.

>>> from inferhub_client import InferHubClient, ChatMessage, ChatRequest
>>> with InferHubClient("http://localhost:5080/", api_key="sk-...") as client:
...     answer = client.chat(ChatRequest(model="llama3", messages=[ChatMessage("user", "hi")]))
...     print(answer.message.content)
"""

from ._async_client import AsyncInferHubClient
from ._client import InferHubClient
from ._exceptions import (
    InferHubError,
    InferHubOpenAiException,
    InferHubRetrievalException,
)
from ._models import (
    AdminEvent,
    AdminNode,
    ChatMessage,
    ChatRequest,
    ChatResponse,
    ClientRow,
    CollectionDetail,
    CollectionInfo,
    CollectionsResponse,
    DeleteProfileResult,
    DocumentChunk,
    DocumentChunksResponse,
    DocumentDeletion,
    DocumentSummary,
    EmbeddingsRequest,
    EmbeddingsResponse,
    EmbedRequest,
    EmbedResponse,
    EnsureModelResult,
    FileDocument,
    FleetModelMatrix,
    GenerateRequest,
    GenerateResponse,
    ImageContent,
    ImageData,
    ImageEditRequest,
    ImageGenerationRequest,
    ImageOptions,
    ImageResponse,
    ImageVariationRequest,
    InferHubTargetProbe,
    IngestResult,
    MediaJob,
    MediaJobList,
    MediaJobOutput,
    ModelCommandAccepted,
    ModelInfo,
    NodeProfile,
    NodeProfileState,
    NodeStatusResponse,
    PutProfileResult,
    RetrievalOptions,
    SearchHit,
    SearchRequest,
    SearchResponse,
    SpeechAudio,
    SpeechChunk,
    SpeechRequest,
    StatusResponse,
    TagsResponse,
    TextDocument,
    Transcription,
    TranscriptionDocument,
    TranscriptionRequest,
    UsageResponse,
    UsageRow,
    VectorMatch,
    VectorQuery,
    VectorRecord,
    VectorUpsert,
    VideoErrorCodes,
)
from ._version import __version__

__all__ = [
    "__version__",
    "InferHubClient",
    "AsyncInferHubClient",
    "InferHubError",
    "InferHubRetrievalException",
    "InferHubOpenAiException",
    "ChatMessage",
    "ChatRequest",
    "ChatResponse",
    "GenerateRequest",
    "GenerateResponse",
    "EmbedRequest",
    "EmbedResponse",
    "EmbeddingsRequest",
    "EmbeddingsResponse",
    "ModelInfo",
    "TagsResponse",
    "StatusResponse",
    "RetrievalOptions",
    "VectorUpsert",
    "VectorQuery",
    "VectorMatch",
    "VectorRecord",
    "TextDocument",
    "FileDocument",
    "IngestResult",
    "DocumentSummary",
    "DocumentChunk",
    "DocumentChunksResponse",
    "DocumentDeletion",
    "SearchRequest",
    "SearchResponse",
    "SearchHit",
    # Audio (phase 18)
    "TranscriptionRequest",
    "Transcription",
    "TranscriptionDocument",
    "SpeechRequest",
    "SpeechAudio",
    "SpeechChunk",
    # Images (phase 18)
    "ImageOptions",
    "ImageGenerationRequest",
    "ImageEditRequest",
    "ImageVariationRequest",
    "ImageResponse",
    "ImageData",
    "MediaJob",
    "MediaJobOutput",
    "MediaJobList",
    "ImageContent",
    # Admin (phase 18)
    "AdminNode",
    "CollectionInfo",
    "CollectionsResponse",
    "CollectionDetail",
    "NodeProfile",
    "PutProfileResult",
    "DeleteProfileResult",
    "NodeProfileState",
    "ModelCommandAccepted",
    "FleetModelMatrix",
    "EnsureModelResult",
    "UsageResponse",
    "UsageRow",
    "ClientRow",
    "AdminEvent",
    # The node (phase 18)
    "NodeStatusResponse",
    "InferHubTargetProbe",
    "VideoErrorCodes",
]
